version: "3"
services:
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - cowlist
  #   depends_on:
  #     - server
  #   volumes:
  #     - "${PWD}/frontend:/frontend"
  spotrate-api:
    container_name: spotrate-api
    build: ./api
    ports:
      - "3001:5000"
    networks:
      - rate-net
    depends_on:
      spotrate-db:
        condition: service_healthy

    volumes:
      - "./api:/api"
  spotrate-db:
    container_name: spotrate-db
    image: "postgres:latest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotrate
    networks:
      - rate-net
    volumes:
      - "./db/data:/var/lib/postgresql/data postgres"
  
networks:
  rate-net:
    driver: bridge