FROM pypy:3

WORKDIR /api

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# RUN source venv/bin/activate   

EXPOSE 5000

ENV FLASK_APP=main.py

RUN "pip3 install -r requirements.txt"

CMD [ "pypy3", "./main.py" ]

# CMD ["flask", "run"]